name: "01 Hello World"

on:
  workflow_dispatch: # this event triggers manually

jobs:
  say_hello_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"

