name: 03 Parallel Jobs

on:
  workflow_dispatch:

jobs:
  linting: # First job
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        run: echo "Running linting..."

  unit_tests: # Second job
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: echo "Running unit tests..."

  integration_tests: # Third job
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Test Environment
        run: echo "Setting up test environment..."

      - name: Integration Tests
        run: echo "Running integration tests..."